/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.andresusanto.app;

import com.andresusanto.engine.BPCS;
import com.andresusanto.engine.Picture;
import com.andresusanto.engine.Playfair;
import com.andresusanto.engine.Tools;
import com.andresusanto.engine.Vigenere;
import com.andresusanto.option.SpacingOption;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andre
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnEncrypt = new javax.swing.JToggleButton();
        btnDecrypt = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        tabAlgorithm = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        chkVigExtended = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cmbSpacingVig = new javax.swing.JComboBox<>();
        btnVigEncrypt = new javax.swing.JButton();
        btnVigDecrypt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbSpacingPlayfair = new javax.swing.JComboBox<>();
        btnOpen1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crypto Suite - 13512028 Andre Susanto");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Key");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("INPUT");

        txtInput.setColumns(20);
        txtInput.setRows(5);
        jScrollPane2.setViewportView(txtInput);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("OUTPUT");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane3.setViewportView(txtOutput);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Algorithm");

        btnEncrypt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEncrypt.setText("Encrypt");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDecrypt.setText("Decrypt");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        btnOpen.setText("Load ...");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        chkVigExtended.setText("Extended (full ASCII)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Spacing");

        cmbSpacingVig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "No Spacing", "Group By 5" }));

        btnVigEncrypt.setText("Encrypt Any File");
        btnVigEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVigEncryptActionPerformed(evt);
            }
        });

        btnVigDecrypt.setText("Decrypt Any File");
        btnVigDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVigEncryptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSpacingVig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVigEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(chkVigExtended))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(btnVigDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chkVigExtended)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSpacingVig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnVigEncrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVigDecrypt)
                .addContainerGap())
        );

        tabAlgorithm.addTab("Vigenere", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Spacing");

        cmbSpacingPlayfair.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "No Spacing", "Group By 5" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbSpacingPlayfair, 0, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSpacingPlayfair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        tabAlgorithm.addTab("Playfair", jPanel2);

        btnOpen1.setText("Save ...");
        btnOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpen1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Andre Susanto - 13512028");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tabAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKey, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOpen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOpen1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addComponent(btnEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnOpen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnOpen1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabAlgorithm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        String input = txtInput.getText().trim();
        String key = txtKey.getText().trim();
                
        if (key.length() == 0){
            JOptionPane.showMessageDialog(null, "Key length must > 0", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        switch (tabAlgorithm.getSelectedIndex()){
            case 0:{
                if (!chkVigExtended.isSelected()) {
                    input = input.toUpperCase();
                    key = key.toUpperCase();
                }
                
                Vigenere vigenere = new Vigenere(key, chkVigExtended.isSelected(), Tools.intValToSpacingOption(cmbSpacingVig.getSelectedIndex()));
                txtOutput.setText(vigenere.encrypt(input));
            }break;
            case 1:{
                input = input.toUpperCase();
                key = key.toUpperCase();
                
                if (!Playfair.isTextSupported(key)){
                    JOptionPane.showMessageDialog(null, "Key contains unsupported character(s). Playfish allows only A-Z characters", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if (!Playfair.isTextSupported(input)){
                    JOptionPane.showMessageDialog(null, "Input contains unsupported character(s). Playfish allows only A-Z characters", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                Playfair playfair = new Playfair(key, Tools.intValToSpacingOption(cmbSpacingPlayfair.getSelectedIndex()));
                txtOutput.setText(playfair.encrypt(input));
            }break;
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        String key = txtKey.getText().trim();
        String input = txtInput.getText().trim();
                
        if (key.length() == 0){
            JOptionPane.showMessageDialog(null, "Key length must > 0", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        switch (tabAlgorithm.getSelectedIndex()){
            case 0:{
                
                if (!chkVigExtended.isSelected()) key = key.toUpperCase();
                
                Vigenere vigenere = new Vigenere(key, chkVigExtended.isSelected(), Tools.intValToSpacingOption(cmbSpacingVig.getSelectedIndex()));
                
                txtOutput.setText(vigenere.decrypt(input));
            }break;
            case 1:{
                input = input.toUpperCase();
                key = key.toUpperCase();
                
                if (!Playfair.isTextSupported(key)){
                    JOptionPane.showMessageDialog(null, "Key contains unsupported character(s). Playfish allows only A-Z characters", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }else if (!Playfair.isTextSupported(input)){
                    JOptionPane.showMessageDialog(null, "Input contains unsupported character(s). Playfish allows only A-Z characters", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                
                Playfair playfair = new Playfair(key, Tools.intValToSpacingOption(cmbSpacingPlayfair.getSelectedIndex()));
                txtOutput.setText(playfair.decrypt(input));
            }break;
        }
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Text File (*.txt)", "txt", "text"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            try {
                List<String> content = Files.readAllLines(Paths.get(fc.getSelectedFile().getPath()), Charset.defaultCharset());
                txtInput.setText("");
                for (String line : content) {
                    txtInput.append(line);
                    txtInput.append("\n");
                }
            } catch (IOException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpen1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Text File (*.txt)", "txt", "text"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            String saveLocation = fc.getSelectedFile().getPath();
            if (!saveLocation.endsWith(".txt")) saveLocation += ".txt";
            
            try {
                Files.write(Paths.get(saveLocation),txtOutput.getText().trim().getBytes());
            } catch (IOException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpen1ActionPerformed

    private void btnVigEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVigEncryptActionPerformed
        final JFileChooser fc = new JFileChooser();
        String key = txtKey.getText().trim();
                
        if (key.length() == 0){
            JOptionPane.showMessageDialog(null, "Key length must > 0", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Vigenere vig = new Vigenere(key, true, SpacingOption.DEFAULT);
        
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            try {
                
                byte[] data = Files.readAllBytes(Paths.get(fc.getSelectedFile().getPath()));
                byte[] process;
                
                if (evt.getSource().equals(btnVigEncrypt))
                    process = vig.encrypt(data);
                else
                    process = vig.decrypt(data);
                
                if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
                    Files.write(Paths.get(fc.getSelectedFile().getPath()), process);
                }
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnVigEncryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws Exception {
        
//        Vigenere vig = new Vigenere("KRN", false, SpacingOption.GROUP_5);
//        System.out.println(vig.encrypt("ANDRE SUSANTO ADALAH ANAK YANG PALING KEREN SEDUNIA COY"));
//        System.out.println(vig.decrypt("KEQBV FEJNXKB KUNVRU KENU PNXX CKCVXX XOIRX JRNLASR PYP"));
//        
//        Path path = Paths.get("D:\\crypt.txt");
//        try {
//            byte[] data = Files.readAllBytes(path);
//            
//            byte[] encrypted = vig.decrypt(data);
//            
//            Files.write(Paths.get("D:\\crypt.txt"), encrypted);
//        } catch (IOException ex) {
//            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
//        }

        Picture pic = new Picture("D:\\pengcit\\sampel1.bmp");
        boolean testing[] = new boolean[64];
        
        for (int y = 0; y < 8; y++){
            for (int x = 0; x < 8; x++){
                if (x % 2 == 0 && y % 2 == 0){
                    testing[x + y * 8] = true;
                }else if(x % 2 != 0 && y % 2 != 0){
                    testing[x + y * 8] = true;
                }else{
                    testing[x + y * 8] = false;
                }
            }
        }
        
        pic.setBitPlane(5, 1, Picture.COLOR_RED, testing);
        //for (int i = 0; i < 5251; i++)
        //    pic.getBitPlane(i, 0, Picture.COLOR_BLUE);
        //pic.save("D:\\pengcit\\sampel1_edit.bmp");
        
        
        boolean plane[] = pic.getBitPlane(5, 1, Picture.COLOR_RED);
        
        for (int y = 0; y < 8; y++){
            for (int x = 0; x < 8; x++){
                if (plane[x + y * 8])
                    System.out.print("1 ");
                else
                    System.out.print("0 ");
            }
            System.out.println();
        }
        System.out.println();
        BPCS bpcs = new BPCS("ANDRE", pic, 0.3f);
        //System.out.println(bpcs.calculateComplexity(plane, 1, Picture.COLOR_RED));

        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                FrmMain frmMain = new FrmMain();
                frmMain.setLocation(dim.width/2-frmMain.getSize().width/2, dim.height/2-frmMain.getSize().height/2);
                frmMain.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JToggleButton btnEncrypt;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnOpen1;
    private javax.swing.JButton btnVigDecrypt;
    private javax.swing.JButton btnVigEncrypt;
    private javax.swing.JCheckBox chkVigExtended;
    private javax.swing.JComboBox<String> cmbSpacingPlayfair;
    private javax.swing.JComboBox<String> cmbSpacingVig;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabAlgorithm;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
